name: pertarungan
description: "A Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  appwrite: ^24.2.0
  change_app_package_name: ^1.5.0
  dart_ping: ^9.0.1
  flutter:
    sdk: flutter
  flutter_autosize_screen_pro: ^0.0.3
  flutter_launcher_icons: ^0.14.4
  material_symbols_icons: ^4.2928.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/icons/logo.png"
  adaptive_icon_foreground_inset: 0
  min_sdk_android: 21 # android min sdk min:16, default 21

  web:
    generate: true
    image_path: "lib/assets/icons/logo.png"
    background_color: "#000000"
    theme_color: "#FFBF00"
  windows:
    generate: true
    image_path: "lib/assets/icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/icons/logo.png"

flutter:
  uses-material-design: true
